class Constants :
    dtype = {
    'accountNumber': 'str',
    'customerId': 'str',
    'creditLimit': 'float64',
    'availableMoney': 'float64',
    'transactionDateTime': 'str',
    'transactionAmount': 'float64',
    'merchantName': 'str',
    'acqCountry': 'str',
    'merchantCountryCode': 'str',
    'posEntryMode': 'str',
    'posConditionCode': 'str',
    'merchantCategoryCode': 'str',
    'currentExpDate': 'str',
    'accountOpenDate': 'str',
    'dateOfLastAddressChange': 'str',
    'cardCVV': 'str',
    'enteredCVV': 'str',
    'cardLast4Digits': 'str',
    'transactionType': 'str',
    'echoBuffer': 'str',
    'currentBalance': 'float64',
    'merchantCity': 'str',
    'merchantState': 'str',
    'merchantZip': 'str',
    'cardPresent': 'bool',
    'posOnPremises': 'str',
    'recurringAuthInd': 'str',
    'expirationDateKeyInMatch': 'bool',
    'isFraud': 'bool'
}